# Generated by Django 3.0.7 on 2020-06-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('S', 'sale'), ('R', 'rent')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField()),
                ('beds_number', models.PositiveIntegerField()),
                ('garages_number', models.PositiveIntegerField()),
                ('baths_number', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='property')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.Category')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
