# Generated by Django 3.0.7 on 2020-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200619_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='', upload_to='property'),
            preserve_default=False,
        ),
    ]
